// En frontend/js/songs.js
const configuracionCanciones = {
  espanol: [
    { file: 'alejandro-sanz - y-si-fuera-ella.mp3', display: 'Alejandro Sanz - Y Si Fuera Ella', listenUrl: 'https://open.spotify.com/search/Alejandro%20Sanz%20Y%20Si%20Fuera%20Ella', platform: 'spotify' },
    { file: 'alex-ubago - sin-miedo-a-nada.mp3', display: 'Alex Ubago - Sin Miedo A Nada', listenUrl: 'https://open.spotify.com/search/Alex%20Ubago%20Sin%20Miedo%20A%20Nada', platform: 'spotify' },
    { file: 'alvaro-soler - sofia.mp3', display: 'Alvaro Soler - Sofia', listenUrl: 'https://open.spotify.com/search/Alvaro%20Soler%20Sofia', platform: 'spotify' },
    { file: 'amaral - moriria-por-vos.mp3', display: 'Amaral - Moriria Por Vos', listenUrl: 'https://open.spotify.com/search/Amaral%20Moriria%20Por%20Vos', platform: 'spotify' },
    { file: 'amaral - sin-ti-no-soy-nada.mp3', display: 'Amaral - Sin Ti No Soy Nada', listenUrl: 'https://open.spotify.com/search/Amaral%20Sin%20Ti%20No%20Soy%20Nada', platform: 'spotify' },
    { file: 'amistades-peligrosas - me-quedare-solo.mp3', display: 'Amistades Peligrosas - Me Quedare Solo', listenUrl: 'https://open.spotify.com/search/Amistades%20Peligrosas%20Me%20Quedare%20Solo', platform: 'spotify' },
    { file: 'ana-mena - usica-ligera.mp3', display: 'Ana Mena - Música Ligera', listenUrl: 'https://open.spotify.com/search/Ana%20Mena%20Usica%20Ligera', platform: 'spotify' },
    { file: 'andy-y-lucas - tanto-la-queria.mp3', display: 'Andy Y Lucas - Tanto La Queria', listenUrl: 'https://open.spotify.com/search/Andy%20Y%20Lucas%20Tanto%20La%20Queria', platform: 'spotify' },
    { file: 'antonio-orozco - estoy-hecho-de-pedacitos-de-ti.mp3', display: 'Antonio Orozco - Estoy Hecho De Pedacitos De Ti', listenUrl: 'https://open.spotify.com/search/Antonio%20Orozco%20Estoy%20Hecho%20De%20Pedacitos%20De%20Ti', platform: 'spotify' },
    { file: 'baute-y-marta-sanchez - colgando-en-tus-manos.mp3', display: 'Baute Y Marta Sanchez - Colgando En Tus Manos', listenUrl: 'https://open.spotify.com/search/Baute%20Y%20Marta%20Sanchez%20Colgando%20En%20Tus%20Manos', platform: 'spotify' },
    { file: 'bebe - malo.mp3', display: 'Bebe - Malo', listenUrl: 'https://open.spotify.com/search/Bebe%20Malo', platform: 'spotify' },
    { file: 'bizarrap-ft-quevedo - bzrp-session-vol.-52.mp3', display: 'Bizarrap Ft Quevedo - Bzrp Session Vol. 52', listenUrl: 'https://open.spotify.com/search/Bizarrap%20Ft%20Quevedo%20Bzrp%20Session%20Vol%2052', platform: 'spotify' },
    { file: 'bizarrap-y-shakira - bzrp-music-sessions-53.mp3', display: 'Bizarrap Y Shakira - Bzrp Music Sessions 53', listenUrl: 'https://open.spotify.com/search/Bizarrap%20Y%20Shakira%20Bzrp%20Music%20Sessions%2053', platform: 'spotify' },
    { file: 'buika - no-habr-nadie-en-el-mundo.mp3', display: 'Buika - No Habr Nadie En El Mundo', listenUrl: 'https://open.spotify.com/search/Buika%20No%20Habra%20Nadie%20En%20El%20Mundo', platform: 'spotify' },
    { file: 'cabaret-pop - juegos-de-amor.mp3', display: 'Cabaret Pop - Juegos De Amor', listenUrl: 'https://open.spotify.com/search/Cabaret%20Pop%20Juegos%20De%20Amor', platform: 'spotify' },
    { file: 'camilo-sesto - algo-de-mi.mp3', display: 'Camilo Sesto - Algo De Mi', listenUrl: 'https://open.spotify.com/search/Camilo%20Sesto%20Algo%20De%20Mi', platform: 'spotify' },
    { file: 'celia-cruz - la-vida-es-un-carnaval.mp3', display: 'Celia Cruz - La Vida Es Un Carnaval', listenUrl: 'https://open.spotify.com/search/Celia%20Cruz%20La%20Vida%20Es%20Un%20Carnaval', platform: 'spotify' },
    { file: 'celtas-cortos - 20-de-abril.mp3', display: 'Celtas Cortos - 20 De Abril', listenUrl: 'https://open.spotify.com/search/Celtas%20Cortos%2020%20De%20Abril', platform: 'spotify' },
    { file: 'chayanne - torero.mp3', display: 'Chayanne - Torero', listenUrl: 'https://open.spotify.com/search/Chayanne%20Torero', platform: 'spotify' },
    { file: 'chimo-bayo - asi-me-gusta-a-mi.mp3', display: 'Chimo Bayo - Asi Me Gusta A Mi', listenUrl: 'https://open.spotify.com/search/Chimo%20Bayo%20Asi%20Me%20Gusta%20A%20Mi', platform: 'spotify' },
    { file: 'complices-es-por-ti.mp3', display: 'Complices Es Por Ti', listenUrl: 'https://open.spotify.com/search/Complices%20Es%20Por%20Ti', platform: 'spotify' },
    { file: 'coti - nada-fue-un-error.mp3', display: 'Coti - Nada Fue Un Error', listenUrl: 'https://open.spotify.com/search/Coti%20Nada%20Fue%20Un%20Error', platform: 'spotify' },
    { file: 'david-bisbal - digale.mp3', display: 'David Bisbal - Digale', listenUrl: 'https://open.spotify.com/search/David%20Bisbal%20Digale', platform: 'spotify' },
    { file: 'david-bisbal - me-enamore-de-ti.mp3', display: 'David Bisbal - Me Enamore De Ti', listenUrl: 'https://open.spotify.com/search/David%20Bisbal%20Me%20Enamore%20De%20Ti', platform: 'spotify' },
    { file: 'david-de-maria-precisamente-ahora.mp3', display: 'David De Maria Precisamente Ahora', listenUrl: 'https://open.spotify.com/search/David%20De%20Maria%20Precisamente%20Ahora', platform: 'spotify' },
    { file: 'diana-navarro - sola.mp3', display: 'Diana Navarro - Sola', listenUrl: 'https://open.spotify.com/search/Diana%20Navarro%20Sola', platform: 'spotify' },
    { file: 'dinamita-pa-los-pollos - pandilleros.mp3', display: 'Dinamita Pa Los Pollos - Pandilleros ', listenUrl: 'https://open.spotify.com/search/Dinamita%20Pa%20Los%20Pollos%20Pandilleros', platform: 'spotify' },
    { file: 'duncan-dhu - en-algun-lugar.mp3', display: 'Duncan Dhu - En Algun Lugar', listenUrl: 'https://open.spotify.com/search/Duncan%20Dhu%20En%20Algun%20Lugar', platform: 'spotify' },
    { file: 'efecto-pasillo - pan-y-manquilla.mp3', display: 'Efecto Pasillo - Pan Y Mantequilla', listenUrl: 'https://open.spotify.com/search/Efecto%20Pasillo%20Pan%20Y%20Manquilla', platform: 'spotify' },
    { file: 'el-canto-del-loco - la-madre-de-jose.mp3', display: 'El Canto Del Loco - La Madre De Jose', listenUrl: 'https://open.spotify.com/search/El%20Canto%20Del%20Loco%20La%20Madre%20De%20Jose', platform: 'spotify' },
    { file: 'el-chaval-de-la-peca - a-ba-ni-bi.mp3', display: 'El Chaval De La Peca - A Ba Ni Bi', listenUrl: 'https://open.spotify.com/search/El%20Chaval%20De%20La%20Peca%20A%20Ba%20Ni%20Bi', platform: 'spotify' },
    { file: 'el-ultimo-de-la-fila - como-un-burro-amarrado-a-la-puerta-del-baile.mp3', display: 'El Ultimo De La Fila - Como Un Burro Amarrado A La Puerta Del Baile', listenUrl: 'https://open.spotify.com/search/El%20Ultimo%20De%20La%20Fila%20Como%20Un%20Burro%20Amarrado%20A%20La%20Puerta%20Del%20Baile', platform: 'spotify' },
    { file: 'ella-baila-sola - cuando-los-sapos-bailen-flamenco.mp3', display: 'Ella Baila Sola - Cuando Los Sapos Bailen Flamenco', listenUrl: 'https://open.spotify.com/search/Ella%20Baila%20Sola%20Cuando%20Los%20Sapos%20Bailen%20Flamenco', platform: 'spotify' },
    { file: 'estopa - me-quedare.mp3', display: 'Estopa - Me Quedare', listenUrl: 'https://open.spotify.com/search/Estopa%20Me%20Quedare', platform: 'spotify' },
    { file: 'estopa-y-el-bicho-demonios.mp3', display: 'Estopa y El Bicho Demonios', listenUrl: 'https://open.spotify.com/search/Estopa%20y%20El%20Bicho%20Demonios', platform: 'spotify' },
    { file: 'extremoduro - so-payaso.mp3', display: 'Extremoduro - So Payaso', listenUrl: 'https://open.spotify.com/search/Extremoduro%20So%20Payaso', platform: 'spotify' },
    { file: 'fito-y-fitipaldis - por-la-boca-vive-el-pez.mp3', display: 'Fito Y Fitipaldis - Por La Boca Vive El Pez', listenUrl: 'https://open.spotify.com/search/Fito%20Y%20Fitipaldis%20Por%20La%20Boca%20Vive%20El%20Pez', platform: 'spotify' },
    { file: 'gabinete-caligari - al-calor-de-un-amor-en-un-bar-.mp3', display: 'Gabinete Caligari -  Al Calor De Un Amor En Un Bar ', listenUrl: 'https://open.spotify.com/search/Gabinete%20Caligari%20Al%20Calor%20De%20Un%20Amor%20En%20Un%20Bar', platform: 'spotify' },
    { file: 'gloria-estefan - mi-tierra.mp3', display: 'Gloria Estefan - Mi Tierra', listenUrl: 'https://open.spotify.com/search/Gloria%20Estefan%20Mi%20Tierra', platform: 'spotify' },
    { file: 'gloria-trevi - todos-me-miran-.mp3', display: 'Gloria Trevi - Todos Me Miran ', listenUrl: 'https://open.spotify.com/search/Gloria%20Trevi%20Todos%20Me%20Miran', platform: 'spotify' },
    { file: 'heroes-del-silencio - heroe-de-leyenda.mp3', display: 'Heroes Del Silencio - Heroe De Leyenda', listenUrl: 'https://open.spotify.com/search/Heroes%20Del%20Silencio%20Heroe%20De%20Leyenda', platform: 'spotify' },
    { file: 'janette - por-que-te-vas.mp3', display: 'Janette - Por Que Te Vas', listenUrl: 'https://open.spotify.com/search/Janette%20Por%20Que%20Te%20Vas', platform: 'spotify' },
    { file: 'jarabe-de-palo - el-lado-oscuro.mp3', display: 'Jarabe De Palo - El Lado Oscuro', listenUrl: 'https://open.spotify.com/search/Jarabe%20De%20Palo%20El%20Lado%20Oscuro', platform: 'spotify' },
    { file: 'jarabe-de-palo - la-flaca.mp3', display: 'Jarabe De Palo - La Flaca', listenUrl: 'https://open.spotify.com/search/Jarabe%20De%20Palo%20La%20Flaca', platform: 'spotify' },
    { file: 'joan-sebastian-ft.-lucero - golondrinas-viajeras.mp3', display: 'Joan Sebastian Ft. Lucero - Golondrinas Viajeras', listenUrl: 'https://open.spotify.com/search/Joan%20Sebastian%20Ft%20Lucero%20Golondrinas%20Viajeras', platform: 'spotify' },
    { file: 'juan-luis-guerra - ojala-que-llueva-cafe.mp3', display: 'Juan Luis Guerra - Ojala Que Llueva Cafe', listenUrl: 'https://open.spotify.com/search/Juan%20Luis%20Guerra%20Ojala%20Que%20Llueva%20Cafe', platform: 'spotify' },
    { file: 'juanes - la-camisa-negra.mp3', display: 'Juanes - La Camisa Negra', listenUrl: 'https://open.spotify.com/search/Juanes%20La%20Camisa%20Negra', platform: 'spotify' },
    { file: 'julieta-venegas - limon-y-sal.mp3', display: 'Julieta Venegas - Limon Y Sal', listenUrl: 'https://open.spotify.com/search/Julieta%20Venegas%20Limon%20Y%20Sal', platform: 'spotify' },
    { file: 'julieta-venegas - me-voy.mp3', display: 'Julieta Venegas - Me Voy', listenUrl: 'https://open.spotify.com/search/Julieta%20Venegas%20Me%20Voy', platform: 'spotify' },
    { file: 'karol-g - si-antes-te-hubiera-conocido.mp3', display: 'Karol G - Si Antes Te Hubiera Conocido', listenUrl: 'https://open.spotify.com/search/Karol%20G%20Si%20Antes%20Te%20Hubiera%20Conocido', platform: 'spotify' },
    { file: 'kiko-y-shara - puede-ser.mp3', display: 'Kiko Y Shara - Puede Ser', listenUrl: 'https://open.spotify.com/search/Kiko%20Y%20Shara%20Puede%20Ser', platform: 'spotify' },
    { file: 'la-guardia - mil-calles-llevan-hacia-ti.mp3', display: 'La Guardia - Mil Calles Llevan Hacia Ti', listenUrl: 'https://open.spotify.com/search/La%20Guardia%20Mil%20Calles%20Llevan%20Hacia%20Ti', platform: 'spotify' },
    { file: 'la-oreja-de-van-gogh - rosas.mp3', display: 'La Oreja De Van Gogh - Rosas', listenUrl: 'https://open.spotify.com/search/La%20Oreja%20De%20Van%20Gogh%20Rosas', platform: 'spotify' },
    { file: 'la-union - lobo-hombre-en-paris.mp3', display: 'La Union - Lobo Hombre En Paris', listenUrl: 'https://open.spotify.com/search/La%20Union%20Lobo%20Hombre%20En%20Paris', platform: 'spotify' },
    { file: 'las-grecas - te-estoy-amando-locamente.mp3', display: 'Las Grecas - Te Estoy Amando Locamente', listenUrl: 'https://open.spotify.com/search/Las%20Grecas%20Te%20Estoy%20Amando%20Locamente', platform: 'spotify' },
    { file: 'laura-pausini - la-soledad.mp3', display: 'Laura Pausini - La Soledad', listenUrl: 'https://open.spotify.com/search/Laura%20Pausini%20La%20Soledad', platform: 'spotify' },
    { file: 'locomia - locomia.mp3', display: 'Locomia - Locomia', listenUrl: 'https://open.spotify.com/search/Locomia%20Locomia', platform: 'spotify' },
    { file: 'loquillo - cadillac-solitario.mp3', display: 'Loquillo - Cadillac Solitario', listenUrl: 'https://open.spotify.com/search/Loquillo%20Cadillac%20Solitario', platform: 'spotify' },
    { file: 'los-chichos - la-historia-de-juan-castillo.mp3', display: 'Los Chichos - La Historia De Juan Castillo', listenUrl: 'https://open.spotify.com/search/Los%20Chichos%20La%20Historia%20De%20Juan%20Castillo', platform: 'spotify' },
    { file: 'los-secretos - pero-a-tu-lado.mp3', display: 'Los Secretos - Pero A Tu Lado', listenUrl: 'https://open.spotify.com/search/Los%20Secretos%20Pero%20A%20Tu%20Lado', platform: 'spotify' },
    { file: 'los-toreros-muertos - mi-aguita-amarilla.mp3', display: 'Los Toreros Muertos - Mi Aguita Amarilla', listenUrl: 'https://open.spotify.com/search/Los%20Toreros%20Muertos%20Mi%20Aguita%20Amarilla', platform: 'spotify' },
    { file: 'luis-fonsi - despacito.mp3', display: 'Luis Fonsi - Despacito', listenUrl: 'https://open.spotify.com/search/Luis%20Fonsi%20Despacito', platform: 'spotify' },
    { file: 'luz-casal - te-deje-marchar.mp3', display: 'Luz Casal - Te Deje Marchar', listenUrl: 'https://open.spotify.com/search/Luz%20Casal%20Te%20Deje%20Marchar', platform: 'spotify' },
    { file: 'm-clan - carolina.mp3', display: 'M Clan - Carolina', listenUrl: 'https://open.spotify.com/search/M%20Clan%20Carolina', platform: 'spotify' },
    { file: 'macaco - moving.mp3', display: 'Macaco - Moving', listenUrl: 'https://open.spotify.com/search/Macaco%20Moving', platform: 'spotify' },
    { file: 'magneto - vuela,-vuela.mp3', display: 'Magneto - Vuela, Vuela', listenUrl: 'https://open.spotify.com/search/Magneto%20Vuela%20Vuela', platform: 'spotify' },
    { file: 'mana - el-muelle-de-san-blas.mp3', display: 'Mana - El Muelle De San Blas', listenUrl: 'https://open.spotify.com/search/Mana%20El%20Muelle%20De%20San%20Blas', platform: 'spotify' },
    { file: 'manolo-escobar - que-viva-espana.mp3', display: 'Manolo Escobar - Que Viva Espana', listenUrl: 'https://open.spotify.com/search/Manolo%20Escobar%20Que%20Viva%20Espana', platform: 'spotify' },
    { file: 'manolo-garcia - pajaros-de-barro.mp3', display: 'Manolo Garcia - Pajaros De Barro', listenUrl: 'https://open.spotify.com/search/Manolo%20Garcia%20Pajaros%20De%20Barro', platform: 'spotify' },
    { file: 'manuel-carrasco - que-bonito-es-querer.mp3', display: 'Manuel Carrasco - Que Bonito Es Querer', listenUrl: 'https://open.spotify.com/search/Manuel%20Carrasco%20Que%20Bonito%20Es%20Querer', platform: 'spotify' },
    { file: 'marc-anthony - valio-la-pena.mp3', display: 'Marc Anthony - Valio La Pena', listenUrl: 'https://open.spotify.com/search/Marc%20Anthony%20Valio%20La%20Pena', platform: 'spotify' },
    { file: 'marc-anthony - vivir-mi-vida.mp3', display: 'Marc Anthony - Vivir Mi Vida', listenUrl: 'https://open.spotify.com/search/Marc%20Anthony%20Vivir%20Mi%20Vida', platform: 'spotify' },
    { file: 'mecano - me-cuesta-tanto-olvidarte.mp3', display: 'Mecano - Me Cuesta Tanto Olvidarte', listenUrl: 'https://open.spotify.com/search/Mecano%20Me%20Cuesta%20Tanto%20Olvidarte', platform: 'spotify' },
    { file: 'miguel-rios - santa-lucia.mp3', display: 'Miguel Rios - Santa Lucia', listenUrl: 'https://open.spotify.com/search/Miguel%20Rios%20Santa%20Lucia', platform: 'spotify' },
    { file: 'molotov - gimme-tha-power.mp3', display: 'Molotov - Gimme Tha Power', listenUrl: 'https://open.spotify.com/search/Molotov%20Gimme%20Tha%20Power', platform: 'spotify' },
    { file: 'monica-naranjo - europa.mp3', display: 'Monica Naranjo - Europa', listenUrl: 'https://open.spotify.com/search/Monica%20Naranjo%20Europa', platform: 'spotify' },
    { file: 'monica-naranjo - sobrevivire.mp3', display: 'Monica Naranjo - Sobrevivire', listenUrl: 'https://open.spotify.com/search/Monica%20Naranjo%20Sobrevivire', platform: 'spotify' },
    { file: 'morat - como-te-atreves.mp3', display: 'Morat - Como Te Atreves', listenUrl: 'https://open.spotify.com/search/Morat%20Como%20Te%20Atreves', platform: 'spotify' },
    { file: 'nacho-cano-y-mercedes-ferrer - vivimos-siempre-juntos.mp3', display: 'Nacho Cano Y Mercedes Ferrer - Vivimos Siempre Juntos', listenUrl: 'https://open.spotify.com/search/Nacho%20Cano%20Y%20Mercedes%20Ferrer%20Vivimos%20Siempre%20Juntos', platform: 'spotify' },
    { file: 'navajita-platea - frio-sin-ti.mp3', display: 'Navajita Platea - Frio Sin Ti', listenUrl: 'https://open.spotify.com/search/Navajita%20Platea%20Frio%20Sin%20Ti', platform: 'spotify' },
    { file: 'navajita-platea - noches-de-bohemia.mp3', display: 'Navajita Platea - Noches De Bohemia', listenUrl: 'https://open.spotify.com/search/Navajita%20Platea%20Noches%20De%20Bohemia', platform: 'spotify' },
    { file: 'nena-daconte - tenia-tanto-que-darte.mp3', display: 'Nena Daconte - Tenia Tanto Que Darte', listenUrl: 'https://open.spotify.com/search/Nena%20Daconte%20Tenia%20Tanto%20Que%20Darte', platform: 'spotify' },
    { file: 'no-me-pises-que-llevo-chanclas - bolillon.mp3', display: 'No Me Pises Que Llevo Chanclas - Bolillon', listenUrl: 'https://open.spotify.com/search/No%20Me%20Pises%20Que%20Llevo%20Chanclas%20Bolillon', platform: 'spotify' },
    { file: 'obk - historias-de-amor.mp3', display: 'Obk - Historias De Amor', listenUrl: 'https://open.spotify.com/search/Obk%20Historias%20De%20Amor', platform: 'spotify' },
    { file: 'pablo-alboran - solamente-tu.mp3', display: 'Pablo Alboran - Solamente Tu', listenUrl: 'https://open.spotify.com/search/Pablo%20Alboran%20Solamente%20Tu', platform: 'spotify' },
    { file: 'pablo-lopez - tu-enemigo.mp3', display: 'Pablo Lopez - Tu Enemigo', listenUrl: 'https://open.spotify.com/search/Pablo%20Lopez%20Tu%20Enemigo', platform: 'spotify' },
    { file: 'radio-futura - escuela-de-calor.mp3', display: 'Radio Futura - Escuela De Calor', listenUrl: 'https://open.spotify.com/search/Radio%20Futura%20Escuela%20De%20Calor', platform: 'spotify' },
    { file: 'raphael - mi-gran-noche.mp3', display: 'Raphael - Mi Gran Noche', listenUrl: 'https://open.spotify.com/search/Raphael%20Mi%20Gran%20Noche', platform: 'spotify' },
    { file: 'revolver - el-roce-de-tu-piel-(en-directo-).mp3', display: 'Revolver - El Roce De Tu Piel (En Directo )', listenUrl: 'https://open.spotify.com/search/Revolver%20El%20Roce%20De%20Tu%20Piel%20En%20Directo', platform: 'spotify' },
    { file: 'revolver - el-roce-de-tu-piel.mp3', display: 'Revolver - El Roce De Tu Piel', listenUrl: 'https://open.spotify.com/search/Revolver%20El%20Roce%20De%20Tu%20Piel', platform: 'spotify' },
    { file: 'revólver - el-roce-de-tu-piel.mp3', display: 'Revólver - El Roce De Tu Piel', listenUrl: 'https://open.spotify.com/search/Revolver%20El%20Roce%20De%20Tu%20Piel', platform: 'spotify' },
    { file: 'ricky-martin - maria-.mp3', display: 'Ricky Martin - Maria ', listenUrl: 'https://open.spotify.com/search/Ricky%20Martin%20Maria', platform: 'spotify' },
    { file: 'rocio-durcal - la-gata-bajo-la-lluvia-.mp3', display: 'Rocio Durcal - La Gata Bajo La Lluvia ', listenUrl: 'https://open.spotify.com/search/Rocio%20Durcal%20La%20Gata%20Bajo%20La%20Lluvia', platform: 'spotify' },
    { file: 'rocio-jurado - muera-el-amor.mp3', display: 'Rocio Jurado - Muera El Amor', listenUrl: 'https://open.spotify.com/search/Rocio%20Jurado%20Muera%20El%20Amor', platform: 'spotify' },
    { file: 'rosalia - despecha.mp3', display: 'Rosalia - Despecha', listenUrl: 'https://open.spotify.com/search/Rosalia%20Despecha', platform: 'spotify' },
    { file: 'rosana - si-tu-no-estas.mp3', display: 'Rosana - Si Tu No Estas', listenUrl: 'https://open.spotify.com/search/Rosana%20Si%20Tu%20No%20Estas', platform: 'spotify' },
    { file: 'rozalen - la-puerta-violeta.mp3', display: 'Rozalen - La Puerta Violeta', listenUrl: 'https://open.spotify.com/search/Rozalen%20La%20Puerta%20Violeta', platform: 'spotify' },
    { file: 'sabina - 19-dias-y-500-noches.mp3', display: 'Sabina 19 Dias y 500 Noches', listenUrl: 'https://open.spotify.com/search/Sabina%2019%20Dias%20y%20500%20Noches', platform: 'spotify' },
    { file: 'seguridad-social - chiquilla.mp3', display: 'Seguridad Social - Chiquilla', listenUrl: 'https://open.spotify.com/search/Seguridad%20Social%20Chiquilla', platform: 'spotify' },
    { file: 'shakira - ciega,-sordomuda.mp3', display: 'Shakira - Ciega, Sordomuda', listenUrl: 'https://open.spotify.com/search/Shakira%20Ciega%20Sordomuda', platform: 'spotify' },
    { file: 'tam-tam-go! - espaldas-mojadas.mp3', display: 'Tam Tam Go! - Espaldas Mojadas', listenUrl: 'https://open.spotify.com/search/Tam%20Tam%20Go%20Espaldas%20Mojadas', platform: 'spotify' },
    { file: 'thalia - arrasando.mp3', display: 'Thalia - Arrasando', listenUrl: 'https://open.spotify.com/search/Thalia%20Arrasando', platform: 'spotify' },
    { file: 'tino-casal - eloise.mp3', display: 'Tino Casal - Eloise', listenUrl: 'https://open.spotify.com/search/Tino%20Casal%20Eloise', platform: 'spotify' },
    { file: 'triana - una-noche-de-amor-desesperada.mp3', display: 'Triana - Una Noche De Amor Desesperada', listenUrl: 'https://open.spotify.com/search/Triana%20Una%20Noche%20De%20Amor%20Desesperada', platform: 'spotify' },
    { file: 'vicco - nochentera.mp3', display: 'Vicco - Nochentera', listenUrl: 'https://open.spotify.com/search/Vicco%20Nochentera', platform: 'spotify' },
    { file: 'zzoilo-y-aitana - mon-amour.mp3', display: 'Zzoilo Y Aitana - Mon Amour', listenUrl: 'https://open.spotify.com/search/Zzoilo%20Y%20Aitana%20Mon%20Amour', platform: 'spotify' },
  ],
  ingles: [
    { file: 'queen - bohemian-rhapsody.mp3', display: 'Queen - Bohemian Rhapsody', listenUrl: 'https://open.spotify.com/search/Queen%20Bohemian%20Rhapsody', platform: 'spotify' },
    { file: 'nirvana - smells-like-teen-spirit.mp3', display: 'Nirvana - Smells Like Teen Spirit', listenUrl: 'https://open.spotify.com/search/Nirvana%20Smells%20Like%20Teen%20Spirit', platform: 'spotify' },
    { file: 'michael-jackson - billie-jean.mp3', display: 'Michael Jackson - Billie Jean', listenUrl: 'https://open.spotify.com/search/Michael%20Jackson%20Billie%20Jean', platform: 'spotify' },
    { file: 'the-beatles - hey-jude.mp3', display: 'The Beatles - Hey Jude', listenUrl: 'https://open.spotify.com/search/The%20Beatles%20Hey%20Jude', platform: 'spotify' },
    { file: 'eagles - hotel-california.mp3', display: 'Eagles - Hotel California', listenUrl: 'https://open.spotify.com/search/Eagles%20Hotel%20California', platform: 'spotify' },
    { file: 'adele - rolling-in-the-deep.mp3', display: 'Adele - Rolling in the Deep', listenUrl: 'https://open.spotify.com/search/Adele%20Rolling%20in%20the%20Deep', platform: 'spotify' },
    { file: 'coldplay - viva-la-vida.mp3', display: 'Coldplay - Viva La Vida', listenUrl: 'https://open.spotify.com/search/Coldplay%20Viva%20La%20Vida', platform: 'spotify' },
    { file: 'ed-sheeran - shape-of-you.mp3', display: 'Ed Sheeran - Shape of You', listenUrl: 'https://open.spotify.com/search/Ed%20Sheeran%20Shape%20of%20You', platform: 'spotify' },
    { file: 'dua-lipa - don-t-start-now.mp3', display: 'Dua Lipa - Don\'t Start Now', listenUrl: 'https://open.spotify.com/search/Dua%20Lipa%20Don%27t%20Start%20Now', platform: 'spotify' },
    { file: 'the-weeknd - blinding-lights.mp3', display: 'The Weeknd - Blinding Lights', listenUrl: 'https://open.spotify.com/search/The%20Weeknd%20Blinding%20Lights', platform: 'spotify' },
    { file: 'billie-eilish - bad-guy.mp3', display: 'Billie Eilish - Bad Guy', listenUrl: 'https://open.spotify.com/search/Billie%20Eilish%20Bad%20Guy', platform: 'spotify' },
    { file: 'imagine-dragons - radioactive.mp3', display: 'Imagine Dragons - Radioactive', listenUrl: 'https://open.spotify.com/search/Imagine%20Dragons%20Radioactive', platform: 'spotify' },
    { file: 'bruno-mars - uptown-funk.mp3', display: 'Bruno Mars - Uptown Funk', listenUrl: 'https://open.spotify.com/search/Bruno%20Mars%20Uptown%20Funk', platform: 'spotify' },
    { file: 'maroon-5 - sugar.mp3', display: 'Maroon 5 - Sugar', listenUrl: 'https://open.spotify.com/search/Maroon%205%20Sugar', platform: 'spotify' },
    { file: 'rihanna - umbrella.mp3', display: 'Rihanna - Umbrella', listenUrl: 'https://open.spotify.com/search/Rihanna%20Umbrella', platform: 'spotify' },
    { file: 'beyonce - single-ladies.mp3', display: 'Beyoncé - Single Ladies', listenUrl: 'https://open.spotify.com/search/Beyonce%20Single%20Ladies', platform: 'spotify' },
    { file: 'kanye-west - stronger.mp3', display: 'Kanye West - Stronger', listenUrl: 'https://open.spotify.com/search/Kanye%20West%20Stronger', platform: 'spotify' },
    { file: 'taylor-swift - shake-it-off.mp3', display: 'Taylor Swift - Shake It Off', listenUrl: 'https://open.spotify.com/search/Taylor%20Swift%20Shake%20It%20Off', platform: 'spotify' },
    { file: 'justin-bieber - sorry.mp3', display: 'Justin Bieber - Sorry', listenUrl: 'https://open.spotify.com/search/Justin%20Bieber%20Sorry', platform: 'spotify' },
    { file: 'ariana-grande - thank-u-next.mp3', display: 'Ariana Grande - Thank U, Next', listenUrl: 'https://open.spotify.com/search/Ariana%20Grande%20Thank%20U%20Next', platform: 'spotify' }
  ],
  peliculas: [
    { file: '1492-la-conquista-del-paraiso - 1992.mp3', display: '1492 La Conquista del Paraíso - 1992', listenUrl: 'https://www.youtube.com/results?search_query=1492+La+Conquista+del+Paraiso+1992', platform: 'youtube' },
    { file: '2001-una-odisea-del-espacio - 1968.mp3', display: '2001 Una Odisea del Espacio - 1968', listenUrl: 'https://www.youtube.com/results?search_query=2001+Una+Odisea+del+Espacio+1968', platform: 'youtube' },
    { file: '50-primeras-citas - 2004.mp3', display: '50 Primeras Citas - 2004', listenUrl: 'https://www.youtube.com/results?search_query=50+Primeras+Citas+2004', platform: 'youtube' },
    { file: 'amelie - 2001.mp3', display: 'Amelie - 2001', listenUrl: 'https://www.youtube.com/results?search_query=Amelie+2001', platform: 'youtube' },
    { file: 'atrapame-si-puedes - 2002.mp3', display: 'Atrápame Si Puedes - 2002', listenUrl: 'https://www.youtube.com/results?search_query=Atrapame+Si+Puedes+2002', platform: 'youtube' },
    { file: 'avatar - 2009.mp3', display: 'Avatar - 2009', listenUrl: 'https://www.youtube.com/results?search_query=Avatar+2009', platform: 'youtube' },
    { file: 'blade-runner - 1982.mp3', display: 'Blade Runner - 1982', listenUrl: 'https://www.youtube.com/results?search_query=Blade+Runner+1982', platform: 'youtube' },
    { file: 'braveheart - 1995.mp3', display: 'Braveheart - 1995', listenUrl: 'https://www.youtube.com/results?search_query=Braveheart+1995', platform: 'youtube' },
    { file: 'cabaret - 1972.mp3', display: 'Cabaret - 1972', listenUrl: 'https://www.youtube.com/results?search_query=Cabaret+1972', platform: 'youtube' },
    { file: 'cantando-bajo-la-lluvia - 1952.mp3', display: 'Cantando Bajo la Lluvia - 1952', listenUrl: 'https://www.youtube.com/results?search_query=Cantando+Bajo+la+Lluvia+1952', platform: 'youtube' },
    { file: 'carros-de-fuego - 1981.mp3', display: 'Carros de Fuego - 1981', listenUrl: 'https://www.youtube.com/results?search_query=Carros+de+Fuego+1981', platform: 'youtube' },
    { file: 'casablanca - 1942.mp3', display: 'Casablanca - 1942', listenUrl: 'https://www.youtube.com/results?search_query=Casablanca+1942', platform: 'youtube' },
    { file: 'cazafantasmas - 1984.mp3', display: 'Cazafantasmas - 1984', listenUrl: 'https://www.youtube.com/results?search_query=Cazafantasmas+1984', platform: 'youtube' },
    { file: 'conan-el-barbaro - 1982.mpay', display: 'Conan el Bárbaro - 1982', listenUrl: 'https://www.youtube.com/results?search_query=Conan+el+Barbaro+1982', platform: 'youtube' },
    { file: 'dirty-dancing - 1987.mp3', display: 'Dirty Dancing - 1987', listenUrl: 'https://www.youtube.com/results?search_query=Dirty+Dancing+1987', platform: 'youtube' },
    { file: 'el-bueno-el-feo-y-el-malo - 1966.mp3', display: 'El Bueno, el Feo y el Malo - 1966', listenUrl: 'https://www.youtube.com/results?search_query=El+Bueno+el+Feo+y+el+Malo+1966', platform: 'youtube' },
    { file: 'el-graduado - 1967.mp3', display: 'El Graduado - 1967', listenUrl: 'https://www.youtube.com/results?search_query=El+Graduado+1967', platform: 'youtube' },
    { file: 'el-guardaespaldas - 1992.mp3', display: 'El Guardaespaldas - 1992', listenUrl: 'https://www.youtube.com/results?search_query=El+Guardaespaldas+1992', platform: 'youtube' },
    { file: 'el-mago-de-oz - 1939.mp3', display: 'El Mago de Oz - 1939', listenUrl: 'https://www.youtube.com/results?search_query=El+Mago+de+Oz+1939', platform: 'youtube' },
    { file: 'el-padrino - 1972.mp3', display: 'El Padrino - 1972', listenUrl: 'https://www.youtube.com/results?search_query=El+Padrino+1972', platform: 'youtube' },
    { file: 'el-puente-sobre-el-rio-kwai - 1957.mp3', display: 'El Puente Sobre el Río Kwai - 1957', listenUrl: 'https://www.youtube.com/results?search_query=El+Puente+Sobre+el+Rio+Kwai+1957', platform: 'youtube' },
    { file: 'el-senor-de-los-anillos - 2001.mp3', display: 'El Señor de los Anillos - 2001', listenUrl: 'https://www.youtube.com/results?search_query=El+Senor+de+los+Anillos+2001', platform: 'youtube' },
    { file: 'flashdance - 1983.mp3', display: 'Flashdance - 1983', listenUrl: 'https://www.youtube.com/results?search_query=Flashdance+1983', platform: 'youtube' },
    { file: 'footloose - 1984.mp3', display: 'Footloose - 1984', listenUrl: 'https://www.youtube.com/results?search_query=Footloose+1984', platform: 'youtube' },
    { file: 'forrest-gump - 1994.mp3', display: 'Forrest Gump - 1994', listenUrl: 'https://www.youtube.com/results?search_query=Forrest+Gump+1994', platform: 'youtube' },
    { file: 'ghost - 1990.mp3', display: 'Ghost - 1990', listenUrl: 'https://www.youtube.com/results?search_query=Ghost+1990', platform: 'youtube' },
    { file: 'gilda - 1946.mp3', display: 'Gilda - 1946', listenUrl: 'https://www.youtube.com/results?search_query=Gilda+1946', platform: 'youtube' },
    { file: 'gladiator - 2000.mp3', display: 'Gladiator - 2000', listenUrl: 'https://www.youtube.com/results?search_query=Gladiator+2000', platform: 'youtube' },
    { file: 'grease - 1978.mp3', display: 'Grease - 1978', listenUrl: 'https://www.youtube.com/results?search_query=Grease+1978', platform: 'youtube' },
    { file: 'harry-potter - 2001.mp3', display: 'Harry Potter - 2001', listenUrl: 'https://www.youtube.com/results?search_query=Harry+Potter+2001', platform: 'youtube' },
    { file: 'hasta-que-llego-su-hora - 1968.mp3', display: 'Hasta que Llegó su Hora - 1968', listenUrl: 'https://www.youtube.com/results?search_query=Hasta+que+Llego+su+Hora+1968', platform: 'youtube' },
    { file: 'indiana-jones - 1981.mp3', display: 'Indiana Jones - 1981', listenUrl: 'https://www.youtube.com/results?search_query=Indiana+Jones+1981', platform: 'youtube' },
    { file: 'interstellar - 2014.mp3', display: 'Interstellar - 2014', listenUrl: 'https://www.youtube.com/results?search_query=Interstellar+2014', platform: 'youtube' },
    { file: 'james-bond - 1964.mp3', display: 'James Bond - 1964', listenUrl: 'https://www.youtube.com/results?search_query=James+Bond+1964', platform: 'youtube' },
    { file: 'joker - 2019.mp3', display: 'Joker - 2019', listenUrl: 'https://www.youtube.com/results?search_query=Joker+2019', platform: 'youtube' },
    { file: 'kill-bill - 2003.mp3', display: 'Kill Bill - 2003', listenUrl: 'https://www.youtube.com/results?search_query=Kill+Bill+2003', platform: 'youtube' },
    { file: 'kill-bill-2 - 2004.mp3', display: 'Kill Bill 2 - 2004', listenUrl: 'https://www.youtube.com/results?search_query=Kill+Bill+2+2004', platform: 'youtube' },
    { file: 'la-bella-y-la-bestia - 2017.mp3', display: 'La Bella y la Bestia - 2017', listenUrl: 'https://www.youtube.com/results?search_query=La+Bella+y+la+Bestia+2017', platform: 'youtube' },
    { file: 'la-familia-addams - 1991.mp3', display: 'La Familia Addams - 1991', listenUrl: 'https://www.youtube.com/results?search_query=La+Familia+Addams+1991', platform: 'youtube' },
    { file: 'la-historia-interminable - 1984.mp3', display: 'La Historia Interminable - 1984', listenUrl: 'https://www.youtube.com/results?search_query=La+Historia+Interminable+1984', platform: 'youtube' },
    { file: 'la-lista-de-schindler - 1993.mp3', display: 'La Lista de Schindler - 1993', listenUrl: 'https://www.youtube.com/results?search_query=La+Lista+de+Schindler+1993', platform: 'youtube' },
    { file: 'la-mision - 1986.mp3', display: 'La Misión - 1986', listenUrl: 'https://www.youtube.com/results?search_query=La+Mision+1986', platform: 'youtube' },
    { file: 'la-muerte-tenia-un-precio - 1965.mp3', display: 'La Muerte Tenia un Precio - 1965', listenUrl: 'https://www.youtube.com/results?search_query=La+Muerte+Tenia+un+Precio+1965', platform: 'youtube' },
    { file: 'la-mascara-del-zorro - 1998.mp3', display: 'La Máscara del Zorro - 1998', listenUrl: 'https://www.youtube.com/results?search_query=La+Mascara+del+Zorro+1998', platform: 'youtube' },
    { file: 'la-vida-de-brian - 1979.mp3', display: 'La Vida de Brian - 1979', listenUrl: 'https://www.youtube.com/results?search_query=La+Vida+de+Brian+1979', platform: 'youtube' },
    { file: 'la-vida-de-pi - 2012.mp3', display: 'La Vida de Pi - 2012', listenUrl: 'https://www.youtube.com/results?search_query=La+Vida+de+Pi+2012', platform: 'youtube' },
    { file: 'la-vida-en-rosa - 2007.mp3', display: 'La Vida en Rosa - 2007', listenUrl: 'https://www.youtube.com/results?search_query=La+Vida+en+Rosa+2007', platform: 'youtube' },
    { file: 'la-vida-es-bella - 1997.mp3', display: 'La Vida es Bella - 1997', listenUrl: 'https://www.youtube.com/results?search_query=La+Vida+es+Bella+1997', platform: 'youtube' },
    { file: 'leon - 1994.mp3', display: 'León - 1994', listenUrl: 'https://www.youtube.com/results?search_query=Leon+1994', platform: 'youtube' },
    { file: 'mary-poppins - 1964.mp3', display: 'Mary Poppins - 1964', listenUrl: 'https://www.youtube.com/results?search_query=Mary+Poppins+1964', platform: 'youtube' },
    { file: 'memorias-de-africa - 1985.mp3', display: 'Memorias de África - 1985', listenUrl: 'https://www.youtube.com/results?search_query=Memorias+de+Africa+1985', platform: 'youtube' },
    { file: 'mision-imposible - 1996.mp3', display: 'Mision Imposible - 1996', listenUrl: 'https://www.youtube.com/results?search_query=Mision+Imposible+1996', platform: 'youtube' },
    { file: 'philadelphia - 1993.mp3', display: 'Philadelphia - 1993', listenUrl: 'https://www.youtube.com/results?search_query=Philadelphia+1993', platform: 'youtube' },
    { file: 'piratas-del-caribe - 2003.mp3', display: 'Piratas del Caribe - 2003', listenUrl: 'https://www.youtube.com/results?search_query=Piratas+del+Caribe+2003', platform: 'youtube' },
    { file: 'pretty-woman - 1990.mp3', display: 'Pretty Woman - 1990', listenUrl: 'https://www.youtube.com/results?search_query=Pretty+Woman+1990', platform: 'youtube' },
    { file: 'pulp-fiction - 1994.mp3', display: 'Pulp Fiction - 1994', listenUrl: 'https://www.youtube.com/results?search_query=Pulp+Fiction+1994', platform: 'youtube' },
    { file: 'regreso-al-futuro - 1985.mp3', display: 'Regreso al Futuro - 1985', listenUrl: 'https://www.youtube.com/results?search_query=Regreso+al+Futuro+1985', platform: 'youtube' },
    { file: 'regreso-al-futuro-inicio - 1985.mp3', display: 'Regreso al Futuro (Inicio) - 1985', listenUrl: 'https://www.youtube.com/results?search_query=Regreso+al+Futuro+Inicio+1985', platform: 'youtube' },
    { file: 'rocky - 1976.mp3', display: 'Rocky - 1976', listenUrl: 'https://www.youtube.com/results?search_query=Rocky+1976', platform: 'youtube' },
    { file: 'rocky-iii - 1982.mp3', display: 'Rocky III - 1982', listenUrl: 'https://www.youtube.com/results?search_query=Rocky+III+1982', platform: 'youtube' },
    { file: 'saga-crepusculo-amanecer-parte-1 - 2011.mp3', display: 'Saga Crepúsculo Amanecer Parte 1 - 2011', listenUrl: 'https://www.youtube.com/results?search_query=Saga+Crepusculo+Amanecer+Parte+1+2011', platform: 'youtube' },
    { file: 'solo-en-casa - 1990.mp3', display: 'Solo en Casa - 1990', listenUrl: 'https://www.youtube.com/results?search_query=Solo+en+Casa+1990', platform: 'youtube' },
    { file: 'sombrero-de-copa - 1935.mp3', display: 'Sombrero de Copa - 1935', listenUrl: 'https://www.youtube.com/results?search_query=Sombrero+de+Copa+1935', platform: 'youtube' },
    { file: 'sonrisas-y-lagrimas - 1965.mp3', display: 'Sonrisas y Lágrimas - 1965', listenUrl: 'https://www.youtube.com/results?search_query=Sonrisas+y+Lagrimas+1965', platform: 'youtube' },
    { file: 'star-wars - 1977.mp3', display: 'Star Wars - 1977', listenUrl: 'https://www.youtube.com/results?search_query=Star+Wars+1977', platform: 'youtube' },
    { file: 'star-wars-imperial-march - 1977.mp3', display: 'Star Wars (Imperial March) - 1977', listenUrl: 'https://www.youtube.com/results?search_query=Star+Wars+Imperial+March+1977', platform: 'youtube' },
    { file: 'superman - 1978.mp3', display: 'Superman - 1978', listenUrl: 'https://www.youtube.com/results?search_query=Superman+1978', platform: 'youtube' },
    { file: 'tal-como-eramos - 1973.mp3', display: 'Tal Como Éramos - 1973', listenUrl: 'https://www.youtube.com/results?search_query=Tal+Como+Eramos+1973', platform: 'youtube' },
    { file: 'tiburon - 1975.mp3', display: 'Tiburón - 1975', listenUrl: 'https://www.youtube.com/results?search_query=Tiburon+1975', platform: 'youtube' },
    { file: 'titanic - 1997.mp3', display: 'Titanic - 1997', listenUrl: 'https://www.youtube.com/results?search_query=Titanic+1997', platform: 'youtube' },
    { file: 'un-dia-en-nueva-york - 1949.mp3', display: 'Un Día en Nueva York - 1949', listenUrl: 'https://www.youtube.com/results?search_query=Un+Dia+en+Nueva+York+1949', platform: 'youtube' },
    { file: 'west-side-story - 1965.mp3', display: 'West Side Story - 1965', listenUrl: 'https://www.youtube.com/results?search_query=West+Side+Story+1965', platform: 'youtube' },
    { file: 'willow - 1988.mp3', display: 'Willow - 1988', listenUrl: 'https://www.youtube.com/results?search_query=Willow+1988', platform: 'youtube' }
  ],
  //=====================================================================
// CONFIGURACIÓN DE CANCIONES (Fragmento ACTUALIZADO para la categoría 'series')
// REEMPLAZA SOLO la sección 'series' dentro de tu objeto 'configuracionCanciones'.
//=====================================================================
series: [
  { file: 'alf - 1986.mp3', display: 'ALF - 1986', listenUrl: 'https://www.youtube.com/results?search_query=ALF+1986+sintonia', platform: 'youtube' },
  { file: 'alice-in-borderland - 2020.mp3', display: 'Alice in Borderland - 2020', listenUrl: 'https://www.youtube.com/results?search_query=Alice+in+Borderland+2020+sintonia', platform: 'youtube' },
  { file: 'ally-mcbeal - 1997.mp3', display: 'Ally McBeal - 1997', listenUrl: 'https://www.youtube.com/results?search_query=Ally+McBeal+1997+sintonia', platform: 'youtube' },
  { file: 'al-salir-de-clase - 1997.mp3', display: 'Al Salir de Clase - 1997', listenUrl: 'https://www.youtube.com/results?search_query=Al+Salir+de+Clase+1997+sintonia', platform: 'youtube' },
  { file: 'aquellos-maravillosos-años - 1988.mp3', display: 'Aquellos Maravillosos Años - 1988', listenUrl: 'https://www.youtube.com/results?search_query=Aquellos+Maravillosos+Años+1988+sintonia', platform: 'youtube' },
  { file: 'aqui-no-hay-quien-viva - 2003.mp3', display: 'Aquí No Hay Quien Viva - 2003', listenUrl: 'https://www.youtube.com/results?search_query=Aqui+No+Hay+Quien+Viva+2003+sintonia', platform: 'youtube' },
  { file: 'arrow - 2012.mp3', display: 'Arrow - 2012', listenUrl: 'https://www.youtube.com/results?search_query=Arrow+2012+sintonia', platform: 'youtube' },
  { file: 'aida - 2005.mp3', display: 'Aída - 2005', listenUrl: 'https://www.youtube.com/results?search_query=Aída+2005+sintonia', platform: 'youtube' },
  { file: 'beverly-hills-90210 - 1990.mp3', display: 'Beverly Hills, 90210 - 1990', listenUrl: 'https://www.youtube.com/results?search_query=Beverly+Hills+90210+1990+sintonia', platform: 'youtube' },
  { file: 'bonanza - 1956.mp3', display: 'Bonanza - 1956', listenUrl: 'https://www.youtube.com/results?search_query=Bonanza+1956+sintonia', platform: 'youtube' },
  { file: 'breaking-bad - 2008.mp3', display: 'Breaking Bad - 2008', listenUrl: 'https://www.youtube.com/results?search_query=Breaking+Bad+2008+sintonia', platform: 'youtube' },
  { file: 'camera-cafe - 2005.mp3', display: 'Camera Café - 2005', listenUrl: 'https://www.youtube.com/results?search_query=Camera+Cafe+2005+sintonia', platform: 'youtube' },
  { file: 'cheers - 1982.mp3', display: 'Cheers - 1982', listenUrl: 'https://www.youtube.com/results?search_query=Cheers+1982+sintonia', platform: 'youtube' },
  { file: 'colombo - 1968.mp3', display: 'Colombo - 1968', listenUrl: 'https://www.youtube.com/results?search_query=Colombo+1968+sintonia', platform: 'youtube' },
  { file: 'corrupcion-en-miami - 1984.mp3', display: 'Corrupción en Miami - 1984', listenUrl: 'https://www.youtube.com/results?search_query=Corrupción+en+Miami+1984+sintonia', platform: 'youtube' },
  { file: 'cosas-de-casa - 1985.mp3', display: 'Cosas de Casa - 1985', listenUrl: 'https://www.youtube.com/results?search_query=Cosas+de+Casa+1985+sintonia', platform: 'youtube' },
  { file: 'csi-miami - 2002.mp3', display: 'CSI Miami - 2002', listenUrl: 'https://www.youtube.com/results?search_query=CSI+Miami+2002+sintonia', platform: 'youtube' },
  { file: 'curro-jimenez - 1976.mp3', display: 'Curro Jimenez - 1976', listenUrl: 'https://www.youtube.com/results?search_query=Curro+Jimenez+1976+sintonia', platform: 'youtube' },
  { file: 'cuentame-como-paso - 2001.mp3', display: 'Cuéntame Cómo Pasó - 2001', listenUrl: 'https://www.youtube.com/results?search_query=Cuentame+Como+Paso+2001+sintonia', platform: 'youtube' },
  { file: 'dallas - 1978.mp3', display: 'Dallas - 1978', listenUrl: 'https://www.youtube.com/results?search_query=Dallas+1978+sintonia', platform: 'youtube' },
  { file: 'daredevil - 2015.mp3', display: 'Daredevil - 2015', listenUrl: 'https://www.youtube.com/results?search_query=Daredevil+2015+sintonia', platform: 'youtube' },
  { file: 'dinastia - 1981.mp3', display: 'Dinastía - 1981', listenUrl: 'https://www.youtube.com/results?search_query=Dinastia+1981+sintonia', platform: 'youtube' },
  { file: 'el-barco - 2011.mp3', display: 'El Barco - 2011', listenUrl: 'https://www.youtube.com/results?search_query=El+Barco+2011+sintonia', platform: 'youtube' },
  { file: 'el-chavo-del-ocho - 1973.mp3', display: 'El Chavo del Ocho - 1973', listenUrl: 'https://www.youtube.com/results?search_query=El+Chavo+del+Ocho+1973+sintonia', platform: 'youtube' },
  { file: 'el-coche-fantastico - 1982.mp3', display: 'El Coche Fantástico - 1982', listenUrl: 'https://www.youtube.com/results?search_query=El+Coche+Fantastico+1982+sintonia', platform: 'youtube' },
  { file: 'el-equipo-a-intro - 1983.mp3', display: 'El Equipo A Intro - 1983', listenUrl: 'https://www.youtube.com/results?search_query=El+Equipo+A+Intro+1983+sintonia', platform: 'youtube' },
  { file: 'el-equipo-a - 1983.mp3', display: 'El Equipo A - 1983', listenUrl: 'https://www.youtube.com/results?search_query=El+Equipo+A+1983+sintonia', platform: 'youtube' },
  { file: 'el-gran-heroe-americano - 1981.mp3', display: 'El Gran Héroe Americano - 1981', listenUrl: 'https://www.youtube.com/results?search_query=El+Gran+Heroe+Americano+1981+sintonia', platform: 'youtube' },
  { file: 'el-juego-del-calamar - 2021.mp3', display: 'El Juego del Calamar - 2021', listenUrl: 'https://www.youtube.com/results?search_query=El+Juego+del+Calamar+2021+sintonia', platform: 'youtube' },
  { file: 'el-principe - 2016.mp3', display: 'El Príncipe - 2016', listenUrl: 'https://www.youtube.com/results?search_query=El+Principe+2016+sintonia', platform: 'youtube' },
  { file: 'el-santo - 1962.mp3', display: 'El Santo - 1962', listenUrl: 'https://www.youtube.com/results?search_query=El+Santo+1962+sintonia', platform: 'youtube' },
  { file: 'el-secreto-de-puente-viejo - 2011.mp3', display: 'El Secreto de Puente Viejo - 2011', listenUrl: 'https://www.youtube.com/results?search_query=El+Secreto+de+Puente+Viejo+2011+sintonia', platform: 'youtube' },
  { file: 'el-show-de-benny-hill - 1955.mp3', display: 'El Show de Benny Hill - 1955', listenUrl: 'https://www.youtube.com/results?search_query=El+Show+de+Benny+Hill+1955+sintonia', platform: 'youtube' },
  { file: 'expediente-x - 1993.mp3', display: 'Expediente X - 1993', listenUrl: 'https://www.youtube.com/results?search_query=Expediente+X+1993+sintonia', platform: 'youtube' },
  { file: 'falcon-crest - 1981.mp3', display: 'Falcon Crest - 1981', listenUrl: 'https://www.youtube.com/results?search_query=Falcon+Crest+1981+sintonia', platform: 'youtube' },
  { file: 'fama - 1982.mp3', display: 'Fama - 1982', listenUrl: 'https://www.youtube.com/results?search_query=Fama+1982+sintonia', platform: 'youtube' },
  { file: 'farmacia-de-guardia - 1991.mp3', display: 'Farmacia de Guardia - 1991', listenUrl: 'https://www.youtube.com/results?search_query=Farmacia+de+Guardia+1991+sintonia', platform: 'youtube' },
  { file: 'friends - 1994.mp3', display: 'Friends - 1994', listenUrl: 'https://www.youtube.com/results?search_query=Friends+1994+sintonia', platform: 'youtube' },
  { file: 'from - 2022.mp3', display: 'From - 2022', listenUrl: 'https://www.youtube.com/results?search_query=From+2022+sintonia', platform: 'youtube' },
  { file: 'fisica-o-quimica - 2008.mp3', display: 'Física o Química - 2008', listenUrl: 'https://www.youtube.com/results?search_query=Física+o+Química+2008+sintonia', platform: 'youtube' },
  { file: 'hawaii-cinco-0 - 1968.mp3', display: 'Hawaii Cinco-0 - 1968', listenUrl: 'https://www.youtube.com/results?search_query=Hawaii+Cinco-0+1968+sintonia', platform: 'youtube' },
  { file: 'hechizada - 1964.mp3', display: 'Hechizada - 1964', listenUrl: 'https://www.youtube.com/results?search_query=Hechizada+1964+sintonia', platform: 'youtube' },
  { file: 'hospital-central - 2000.mp3', display: 'Hospital Central - 2000', listenUrl: 'https://www.youtube.com/results?search_query=Hospital+Central+2000+sintonia', platform: 'youtube' },
  { file: 'juego-de-tronos - 2011.mp3', display: 'Juego de Tronos - 2011', listenUrl: 'https://www.youtube.com/results?search_query=Juego+de+Tronos+2011+sintonia', platform: 'youtube' },
  { file: 'juzgado-de-guardia - 1984.mp3', display: 'Juzgado de Guardia - 1984', listenUrl: 'https://www.youtube.com/results?search_query=Juzgado+de+Guardia+1984+sintonia', platform: 'youtube' },
  { file: 'jovenes-jinetes - 1989.mp3', display: 'Jóvenes Jinetes - 1989', listenUrl: 'https://www.youtube.com/results?search_query=Jovenes+Jinetes+1989+sintonia', platform: 'youtube' },
  { file: 'kung-fu - 1972.mp3', display: 'Kung Fu - 1972', listenUrl: 'https://www.youtube.com/results?search_query=Kung+Fu+1972+sintonia', platform: 'youtube' },
  { file: 'la-casa-de-la-pradera - 1974.mp3', display: 'La Casa de la Pradera - 1974', listenUrl: 'https://www.youtube.com/results?search_query=La+Casa+de+la+Pradera+1974+sintonia', platform: 'youtube' },
  { file: 'la-casa-de-papel-(intro) - 2017.mp3', display: 'La Casa de Papel (Intro) - 2017', listenUrl: 'https://www.youtube.com/results?search_query=La+Casa+de+Papel+Intro+2017+sintonia', platform: 'youtube' },
  { file: 'la-casa-de-papel - 2017.mp3', display: 'La Casa de Papel - 2017', listenUrl: 'https://www.youtube.com/results?search_query=La+Casa+de+Papel+2017+sintonia', platform: 'youtube' },
  { file: 'la-casa-del-dragon - 2022.mp3', display: 'La Casa del Dragón - 2022', listenUrl: 'https://www.youtube.com/results?search_query=La+Casa+del+Dragón+2022+sintonia', platform: 'youtube' },
  { file: 'la-hora-de-bill-cosby - 1984.mp3', display: 'La Hora de Bill Cosby - 1984', listenUrl: 'https://www.youtube.com/results?search_query=La+Hora+de+Bill+Cosby+1984+sintonia', platform: 'youtube' },
  { file: 'la-que-se-avecina - 2007.mp3', display: 'La Que Se Avecina - 2007', listenUrl: 'https://www.youtube.com/results?search_query=La+Que+Se+Avecina+2007+sintonia', platform: 'youtube' },
  { file: 'la-reina-del-sur - 2011.mp3', display: 'La Reina del Sur - 2011', listenUrl: 'https://www.youtube.com/results?search_query=La+Reina+del+Sur+2011+sintonia', platform: 'youtube' },
  { file: 'la-tribu-de-los-brady - 1969.mp3', display: 'La Tribu de los Brady - 1969', listenUrl: 'https://www.youtube.com/results?search_query=La+Tribu+de+los+Brady+1969+sintonia', platform: 'youtube' },
  { file: 'las-chicas-de-oro - 1985.mp3', display: 'Las Chicas de Oro - 1985', listenUrl: 'https://www.youtube.com/results?search_query=Las+Chicas+de+Oro+1985+sintonia', platform: 'youtube' },
  { file: 'los-colby - 1985.mp3', display: 'Los Colby - 1985', listenUrl: 'https://www.youtube.com/results?search_query=Los+Colby+1985+sintonia', platform: 'youtube' },
  { file: 'los-hombres-de-harrelson - 1975.mp3', display: 'Los Hombres de Harrelson - 1975', listenUrl: 'https://www.youtube.com/results?search_query=Los+Hombres+de+Harrelson+1975+sintonia', platform: 'youtube' },
  { file: 'los-problemas-crecen - 1985.mp3', display: 'Los Problemas Crecen - 1985', listenUrl: 'https://www.youtube.com/results?search_query=Los+Problemas+Crecen+1985+sintonia', platform: 'youtube' },
  { file: 'los-ricos-tambien-lloran - 1979.mp3', display: 'Los Ricos También Lloran - 1979', listenUrl: 'https://www.youtube.com/results?search_query=Los+Ricos+También+Lloran+1979+sintonia', platform: 'youtube' },
  { file: 'los-serrano - 2003.mp3', display: 'Los Serrano - 2003', listenUrl: 'https://www.youtube.com/results?search_query=Los+Serrano+2003+sintonia', platform: 'youtube' },
  { file: 'los-simpson - 1989.mp3', display: 'Los Simpson - 1989', listenUrl: 'https://www.youtube.com/results?search_query=Los+Simpson+1989+sintonia', platform: 'youtube' },
  { file: 'los-vigilantes-de-la-playa - 1989.mp3', display: 'Los Vigilantes de la Playa - 1989', listenUrl: 'https://www.youtube.com/results?search_query=Los+Vigilantes+de+la+Playa+1989+sintonia', platform: 'youtube' },
  { file: 'los-angeles-de-charlie - 1976.mp3', display: 'Los Ángeles de Charlie - 1976', listenUrl: 'https://www.youtube.com/results?search_query=Los+Angeles+de+Charlie+1976+sintonia', platform: 'youtube' },
  { file: 'luz-de-luna - 1985.mp3', display: 'Luz de Luna - 1985', listenUrl: 'https://www.youtube.com/results?search_query=Luz+de+Luna+1985+sintonia', platform: 'youtube' },
  { file: 'macgyver - 1985.mp3', display: 'MacGyver - 1985', listenUrl: 'https://www.youtube.com/results?search_query=MacGyver+1985+sintonia', platform: 'youtube' },
  { file: 'magnum-p.i - 1980.mp3', display: 'Magnum, P.I - 1980', listenUrl: 'https://www.youtube.com/results?search_query=Magnum+P.I+1980+sintonia', platform: 'youtube' },
  { file: 'manos-a-la-obra - 1998.mp3', display: 'Manos a la Obra - 1998', listenUrl: 'https://www.youtube.com/results?search_query=Manos+a+la+Obra+1998+sintonia', platform: 'youtube' },
  { file: 'mash - 1972.mp3', display: 'MASH - 1972', listenUrl: 'https://www.youtube.com/results?search_query=MASH+1972+sintonia', platform: 'youtube' },
  { file: 'matrimonio-con-hijos - 1987.mp3', display: 'Matrimonio con Hijos - 1987', listenUrl: 'https://www.youtube.com/results?search_query=Matrimonio+con+Hijos+1987+sintonia', platform: 'youtube' },
  { file: 'melrose-place - 1992.mp3', display: 'Melrose Place - 1992', listenUrl: 'https://www.youtube.com/results?search_query=Melrose+Place+1992+sintonia', platform: 'youtube' },
  { file: 'mentes-criminales - 2005.mp3', display: 'Mentes Criminales - 2005', listenUrl: 'https://www.youtube.com/results?search_query=Mentes+Criminales+2005+sintonia', platform: 'youtube' },
  { file: 'miercoles - 2022.mp3', display: 'Miércoles - 2022', listenUrl: 'https://www.youtube.com/results?search_query=Miércoles+2022+sintonia', platform: 'youtube' },
  { file: 'medico-de-familia - 1995.mp3', display: 'Médico de Familia - 1995', listenUrl: 'https://www.youtube.com/results?search_query=Médico+de+Familia+1995+sintonia', platform: 'youtube' },
  { file: 'money-heist - 2017.mp3', display: 'La Casa de Papel - 2017', listenUrl: 'https://www.youtube.com/results?search_query=La+Casa+de+Papel+2017+sintonia', platform: 'youtube' }, // Redundante, ajustar si se quiere una única entrada para esta serie
  { file: 'the-office - 2005.mp3', display: 'The Office - 2005', listenUrl: 'https://www.youtube.com/results?search_query=The+Office+2005+sintonia', platform: 'youtube' },
  { file: 'orzowei - 1977.mp3', display: 'Orzowei - 1977', listenUrl: 'https://www.youtube.com/results?search_query=Orzowei+1977+sintonia', platform: 'youtube' },
  { file: 'padres-forzosos - 1987.mp3', display: 'Padres Forzosos - 1987', listenUrl: 'https://www.youtube.com/results?search_query=Padres+Forzosos+1987+sintonia', platform: 'youtube' },
  { file: 'pasapalabra-series - 2000.mp3', display: 'Pasapalabra - 2000', listenUrl: 'https://www.youtube.com/results?search_query=Pasapalabra+2000+sintonia', platform: 'youtube' }, // Posiblemente duplicado con TV, si es solo la sintonía
  { file: 'pesadillas - 1995.mp3', display: 'Pesadillas - 1995', listenUrl: 'https://www.youtube.com/results?search_query=Pesadillas+1995+sintonia', platform: 'youtube' },
  { file: 'primos-lejanos - 1986.mp3', display: 'Primos Lejanos - 1986', listenUrl: 'https://www.youtube.com/results?search_query=Primos+Lejanos+1986+sintonia', platform: 'youtube' },
  { file: 'remington-steele - 1982.mp3', display: 'Remington Steele - 1982', listenUrl: 'https://www.youtube.com/results?search_query=Remington+Steele+1982+sintonia', platform: 'youtube' },
  { file: 'renegado - 1992.mp3', display: 'Renegado - 1992', listenUrl: 'https://www.youtube.com/results?search_query=Renegado+1992+sintonia', platform: 'youtube' },
  { file: 'salvados-por-la-campana - 1989.mp3', display: 'Salvados por la Campana - 1989', listenUrl: 'https://www.youtube.com/results?search_query=Salvados+por+la+Campana+1989+sintonia', platform: 'youtube' },
  { file: 'sandokan - 1976.mp3', display: 'Sandokan - 1976', listenUrl: 'https://www.youtube.com/results?search_query=Sandokan+1976+sintonia', platform: 'youtube' },
  { file: 'santa-barbara - 1984.mp3', display: 'Santa Bárbara - 1984', listenUrl: 'https://www.youtube.com/results?search_query=Santa+Bárbara+1984+sintonia', platform: 'youtube' },
  { file: 'se-ha-escrito-un-crimen - 1984.mp3', display: 'Se Ha Escrito un Crimen - 1984', listenUrl: 'https://www.youtube.com/results?search_query=Se+Ha+Escrito+un+Crimen+1984+sintonia', platform: 'youtube' },
  { file: 'siete-vidas - 1996.mp3', display: 'Siete Vidas - 1996', listenUrl: 'https://www.youtube.com/results?search_query=Siete+Vidas+1996+sintonia', platform: 'youtube' },
  { file: 'silo - 2023.mp3', display: 'Silo - 2023', listenUrl: 'https://www.youtube.com/results?search_query=Silo+2023+sintonia', platform: 'youtube' },
  { file: 'sin-tetas-no-hay-paraiso - 2006.mp3', display: 'Sin Tetas No Hay Paraíso - 2006', listenUrl: 'https://www.youtube.com/results?search_query=Sin+Tetas+No+Hay+Paraíso+2006+sintonia', platform: 'youtube' },
  { file: 'starsky-y-hutch - 1975.mp3', display: 'Starsky y Hutch - 1975', listenUrl: 'https://www.youtube.com/results?search_query=Starsky+y+Hutch+1975+sintonia', platform: 'youtube' },
  { file: 'stranger-things - 2016.mp3', display: 'Stranger Things - 2016', listenUrl: 'https://www.youtube.com/results?search_query=Stranger+Things+2016+sintonia', platform: 'youtube' },
  { file: 'super-agente-86 - 1965.mp3', display: 'Super Agente 86 - 1965', listenUrl: 'https://www.youtube.com/results?search_query=Super+Agente+86+1965+sintonia', platform: 'youtube' },
  { file: 'the-big-bang-theory - 2007.mp3', display: 'The Big Bang Theory - 2007', listenUrl: 'https://www.youtube.com/results?search_query=The+Big+Bang+Theory+2007+sintonia', platform: 'youtube' },
  { file: 'tierra-de-lobos - 2010.mp3', display: 'Tierra de Lobos - 2010', listenUrl: 'https://www.youtube.com/results?search_query=Tierra+de+Lobos+2010+sintonia', platform: 'youtube' },
  { file: 'twin-peaks - 1990.mp3', display: 'Twin Peaks - 1990', listenUrl: 'https://www.youtube.com/results?search_query=Twin+Peaks+1990+sintonia', platform: 'youtube' },
  { file: 'the-walking-dead - 2010.mp3', display: 'The Walking Dead - 2010', listenUrl: 'https://www.youtube.com/results?search_query=The+Walking+Dead+2010+sintonia', platform: 'youtube' },
  { file: 'un-medico-precoz - 1989.mp3', display: 'Un Médico Precoz - 1989', listenUrl: 'https://www.youtube.com/results?search_query=Un+Médico+Precoz+1989+sintonia', platform: 'youtube' },
  { file: 'un-paso-adelante - 2002.mp3', display: 'Un Paso Adelante - 2002', listenUrl: 'https://www.youtube.com/results?search_query=Un+Paso+Adelante+2002+sintonia', platform: 'youtube' },
  { file: 'v - 1984.mp3', display: 'V - 1984', listenUrl: 'https://www.youtube.com/results?search_query=V+1984+sintonia', platform: 'youtube' },
  { file: 'vacaciones-en-el-mar - 1976.mp3', display: 'Vacaciones en el Mar - 1976', listenUrl: 'https://www.youtube.com/results?search_query=Vacaciones+en+el+Mar+1976+sintonia', platform: 'youtube' },
  { file: 'verano-azul - 1981.mp3', display: 'Verano Azul - 1981', listenUrl: 'https://www.youtube.com/results?search_query=Verano+Azul+1981+sintonia', platform: 'youtube' },
  { file: 'webster - 1983.mp3', display: 'Webster - 1983', listenUrl: 'https://www.youtube.com/results?search_query=Webster+1983+sintonia', platform: 'youtube' },
  { file: 'xena-la-princesa-guerrera - 1995.mp3', display: 'Xena, la Princesa Guerrera - 1995', listenUrl: 'https://www.youtube.com/results?search_query=Xena+la+Princesa+Guerrera+1995+sintonia', platform: 'youtube' },
  { file: 'elite - 2018.mp3', display: 'Élite - 2018', listenUrl: 'https://www.youtube.com/results?search_query=Elite+2018+sintonia', platform: 'youtube' }
],
  tv: [
    { file: 'un-dos-tres-sintonia.mp3', display: 'Un, dos, tres... responda otra vez - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=Un+Dos+Tres+Sintonia', platform: 'youtube' },
    { file: 'grand-prix-sintonia.mp3', display: 'Grand Prix del Verano - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=Grand+Prix+Sintonia', platform: 'youtube' },
    { file: 'que-apostamos-sintonia.mp3', display: 'Qué apostamos - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=Que+Apostamos+Sintonia', platform: 'youtube' },
    { file: 'la-bola-de-cristal-bruja-averia.mp3', display: 'La Bola de Cristal - La Bruja Avería', listenUrl: 'https://www.youtube.com/results?search_query=La+Bola+de+Cristal+La+Bruja+Averia', platform: 'youtube' },
    { file: 'el-hormiguero-sintonia.mp3', display: 'El Hormiguero - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=El+Hormiguero+Sintonia', platform: 'youtube' },
    { file: 'saber-y-ganar-sintonia.mp3', display: 'Saber y Ganar - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=Saber+y+Ganar+Sintonia', platform: 'youtube' },
    { file: 'pasapalabra-sintonia.mp3', display: 'Pasapalabra - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=Pasapalabra+Sintonia', platform: 'youtube' },
    { file: 'cuentame-como-paso-sintonia.mp3', display: 'Cuéntame Cómo Pasó - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=Cuentame+Como+Paso+Sintonia', platform: 'youtube' },
    { file: 'farmacia-de-guardia-sintonia.mp3', display: 'Farmacia de Guardia - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=Farmacia+de+Guardia+Sintonia', platform: 'youtube' },
    { file: 'verano-azul-sintonia.mp3', display: 'Verano Azul - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=Verano+Azul+Sintonia', platform: 'youtube' }
  ],
  infantiles: [
    { file: 'dragones-y-mazmorras-sintonia.mp3', display: 'Dragones y Mazmorras - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=Dragones+y+Mazmorras+Sintonia', platform: 'youtube' },
    { file: 'david-el-gnomo-sintonia.mp3', display: 'David el Gnomo - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=David+el+Gnomo+Sintonia', platform: 'youtube' },
    { file: 'd-artacan-sintonia.mp3', display: 'D\'Artacán y los Tres Mosqueperros - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=D%27Artacan+y+los+Tres+Mosqueperros+Sintonia', platform: 'youtube' },
    { file: 'willy-fog-sintonia.mp3', display: 'La Vuelta al Mundo de Willy Fog - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=La+Vuelta+al+Mundo+de+Willy+Fog+Sintonia', platform: 'youtube' },
    { file: 'barrio-sesamo-sintonia.mp3', display: 'Barrio Sésamo - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=Barrio+Sesamo+Sintonia', platform: 'youtube' },
    { file: 'heidi-sintonia.mp3', display: 'Heidi - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=Heidi+Sintonia', platform: 'youtube' },
    { file: 'marco-sintonia.mp3', display: 'Marco - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=Marco+Sintonia', platform: 'youtube' },
    { file: 'mazinger-z-sintonia.mp3', display: 'Mazinger Z - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=Mazinger+Z+Sintonia', platform: 'youtube' },
    { file: 'pokemon-sintonia.mp3', display: 'Pokémon - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=Pokemon+Sintonia', platform: 'youtube' },
    { file: 'digimon-sintonia.mp3', display: 'Digimon - Sintonía', listenUrl: 'https://www.youtube.com/results?search_query=Digimon+Sintonia', platform: 'youtube' }
  ],
  anuncios: [
    { file: 'cola-cao-negrito.mp3', display: 'Cola Cao - Yo soy aquel negrito', listenUrl: 'https://www.youtube.com/results?search_query=Cola+Cao+Yo+soy+aquel+negrito', platform: 'youtube' },
    { file: 'pipas-g-jingle.mp3', display: 'Pipas G - Jingle', listenUrl: 'https://www.youtube.com/results?search_query=Pipas+G+Jingle', platform: 'youtube' },
    { file: 'choco-krispies-desayuno.mp3', display: 'Choco Krispies - El desayuno de los campeones', listenUrl: 'https://www.youtube.com/results?search_query=Choco+Krispies+El+desayuno+de+los+campeones', platform: 'youtube' },
    { file: 'fanta-jingle-90s.mp3', display: 'Fanta - Jingle 90s', listenUrl: 'https://www.youtube.com/results?search_query=Fanta+Jingle+90s', platform: 'youtube' },
    { file: 'la-casera-el-verano-mas-refrescante.mp3', display: 'La Casera - El verano más refrescante', listenUrl: 'https://www.youtube.com/results?search_query=La+Casera+El+verano+mas+refrescante', platform: 'youtube' },
    { file: 'donuts-tengo-los-agujeros.mp3', display: 'Donuts - Tengo los agujeros', listenUrl: 'https://www.youtube.com/results?search_query=Donuts+Tengo+los+agujeros', platform: 'youtube' },
    { file: 'mimosin-suavidad-mimosin.mp3', display: 'Mimosín - Suavidad Mimosín', listenUrl: 'https://www.youtube.com/results?search_query=Mimosin+Suavidad+Mimosin', platform: 'youtube' },
    { file: 'bocatta-que-te-voy-a-dar.mp3', display: 'Bocatta - ¿Qué te voy a dar?', listenUrl: 'https://www.youtube.com/results?search_query=Bocatta+Que+te+voy+a+dar', platform: 'youtube' },
    { file: 'campofrio-la-familia.mp3', display: 'Campofrío - La Familia', listenUrl: 'https://www.youtube.com/results?search_query=Campofrio+La+Familia', platform: 'youtube' },
    { file: 'navidad-el-almendro.mp3', display: 'Navidad - Vuelve a Casa por Navidad (El Almendro)', listenUrl: 'https://www.youtube.com/results?search_query=Navidad+Vuelve+a+Casa+por+Navidad+El+Almendro', platform: 'youtube' }
  ]
};